### ISSUE TITLE
questions for the thaxe force

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/wwx2016#1]
Does the thaxe force members receive a notification when I post here?
Should we advertise this repo to the world?
Where is the website repo?

**Comment by JbIPS** [comment]
I received it! We'll advertise this repo as soon as we announce the WWX2016. The website is currently under the control of @back2dos but we planned to transfer it here.

**Comment by zabojad** [comment]
FYI, I received it too.

**Comment by lexoyo** [comment]
Then you are officially a member of the thaxe force
