### ISSUE TITLE
Kha Returns

### ISSUE THREAD

**Issue by RobDangerous** [silexlabs/wwx2016#10]
Would like to talk some more about Kha, if that's ok.

**Comment by mebyz** [comment]
I'll attend to this talk for sure !

**Comment by ibilon** [comment]
Would you want to do a full talk (~40min) or a lightning talk (~15min) about that?

**Comment by RobDangerous** [comment]
Full talk

**Comment by clemos** [comment]
We're about to finish the website.
Do you mind if we announce your talk on the website ?
If it's ok for you, we can use last year's picture and bio, or you can send us new ones.
We will also need a title for the talk.

**Comment by RobDangerous** [comment]
No problem, that's ok.
"Kha Returns" is the actual title I had in mind.

**Comment by JbIPS** [comment]
Talk announced on website, closing.
