### ISSUE TITLE
Haxe React

### ISSUE THREAD

**Issue by elsassph** [silexlabs/wwx2016#11]
Massive would like to talk about Haxe and React. 
Possibly with chunks of React Native and/or Webpack in it.

**Comment by ibilon** [comment]
Would you want to do a full talk (~40min) or a lightning talk (~15min) about that?

**Comment by elsassph** [comment]
I think we could do a full talk and show some concrete demonstration.

**Comment by clemos** [comment]
We're about to finish the website.
Do you mind if we announce your talk on the website ?
If it's ok for you, we can use last year's picture and bio, or you can send us new ones.
We will also need a title for the talk.

**Comment by dmouton** [comment]
Ooooh this is a very good subject

**Comment by JbIPS** [comment]
Talk's announced (with David Peek). Closing
