### ISSUE TITLE
Unreal.hx: Using Haxe with the Unreal Engine 4

### ISSUE THREAD

**Issue by waneck** [silexlabs/wwx2016#13]
I'd like to have a talk about the project I've been developing with proletariat: https://github.com/proletariatgames/unreal.hx .
We've got quite a lot to talk about this - from being able to leverage the full Unreal C++ ecosystem with Haxe using macros and hxcpp, to the use of cppia to make iteration times negligible

**Comment by ibilon** [comment]
Hey, so full length (40 min) talk?

**Comment by waneck** [comment]
Yes, I believe there is content for a full length talk - from getting started to how it works internally, there's a lot to talk about! :)

**Comment by JbIPS** [comment]
Be sure to keep some time to amaze our eyes with a breath taking live demo! Can we take last year bio and pic to announce your talk?

**Comment by clemos** [comment]
Bump @waneck :)
We'd really like to announce your talk: can we use last year's bio and picture ?

**Comment by JbIPS** [comment]
Hello @waneck !

Could you please fill and / or correct the following infos so we could announce your talk ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks!

---

**Job title / occupation**

**Biography**

**Talk’s title**

**Talk’s focus & description**

**Links relevant about you and your talk**

**Comment by waneck** [comment]
Oh sure, I'll do it tonight! I missed @clemos last message, sorry!

**Comment by waneck** [comment]
**Job title**
Engineer at Proletariat, Inc.
**Biography**
Cauê is the main author of the Java and C# targets. He loves working with game and server development, and exploring the possibilities of Haxe while doing so!
**Talk's title**
Unreal.hx: Unveiling the power of the Unreal Engine with Haxe
**Talk's focus & description**
In this talk, I will present Proletariat's latest library, Unreal.hx, which integrates Haxe into the Unreal Engine in a more feature complete manner than any other language integration, apart from the official C++. I will show how to setup a project, how the project uses macros to achieve this tight integration with the C++ API, and how it uses the cppia VM to leverage faster iteration.
I will discuss also how the created Unreal.hx toolchain might be used to integrate other C++ libraries with Haxe out-of-the-box

**Comment by waneck** [comment]
Links: https://github.com/proletariatgames/unreal.hx

**Comment by ibilon** [comment]
Thanks, I'll add you to the website.

What picture do you want us to use?

**Comment by waneck** [comment]
Well, I don't usually take pictures and I suck at using them. So I've asked my girlfriend to choose it and the choice was this one. Let me know if it works
![770fc114-c35d-45dc-9cd7-4911c174bd12](https://cloud.githubusercontent.com/assets/178171/14387878/c1b4a08c-fd81-11e5-8b41-978dcc1d5504.jpg)

**Comment by ibilon** [comment]
It works ;)

Added to the website.

**Comment by jeebus3000** [comment]
Hello!
Is there a recording of this session?

**Comment by ibilon** [comment]
@jeebus3000 all talks were recorded and will be put online.

**Comment by jeebus3000** [comment]
Cool!
Thanks!

**Comment by ibilon** [comment]
Hey @waneck, couldn't find your presentation online, could you upload it? (or send us a link if I just missed it)
Also would it be ok for us to upload it on the wwx website?

**Comment by waneck** [comment]
Hey! The slides are at https://slides.com/cauewaneck/unreal-hx . I can send you guys an html of this, but I don't think there will be a version that is 100% in the wwx website. Anyway, I'd be of course fine if you can do it.

**Comment by ibilon** [comment]
Thanks,
I think it ended up ok http://wwx.silexlabs.org/2016/assets/presentations/caue-waneck/#/
and almost 100% on the wwx repository.
