### ISSUE TITLE
hexMachina framework

### ISSUE THREAD

**Issue by FrancisBourre** [silexlabs/wwx2016#14]
Hi,

DoclerLabs would be interested to make a presentation about the hexMachina framework.

https://github.com/DoclerLabs/hexIoC

Focuses:

• Modern MVC.
• Dependency injection with annotations.
• Dependency injection with DSL.
• Scalable and expandable event-systems.
• Delegation event model.
• Abstract stateless and stateful services layer.
• Independent service locators driven by injection.
• 3 tier meta-system: Services, modules and UIs.
• Modularity with composite context hierarchy.
• Smart unit-testing.

**Comment by elsassph** [comment]
Yay more frameworks!

**Comment by ibilon** [comment]
Are you looking to do a lightning (15 min) or full (40 min) talk?

**Comment by FrancisBourre** [comment]
A full talk would be really nice, we want to showcase so much things.

**Comment by JbIPS** [comment]
Hello @FrancisBourre, this seems promising! Could you give us a contact at DoclerLabs to talk about a potential partnership with WWX? 

Thank you

**Comment by FrancisBourre** [comment]
Hello @JbIPS Sure, you can contact Melanie.Delannoy@doclerholding.com

**Comment by JbIPS** [comment]
Hello @FrancisBourre ! Could you give us a quick presentation of you and your talk with a nice picture of you? You can get inspiration from the other speakers on the [website](http://wwx.silexlabs.org/2016/#speakers)

**Comment by Neverbirth** [comment]
I have one!

![francis](https://cloud.githubusercontent.com/assets/2273861/13322200/9748f6a6-dbd3-11e5-91bb-4bec0512c86c.gif)

**Comment by FrancisBourre** [comment]
Hello @JbIPS ! Sure. For the picture, if the res is enough, you can take it from my linkedin profile: https://www.linkedin.com/in/francisbourre And the talk title is: "hexMachina: Urban framework for hardcore developers". Thank you so much for all.

**Comment by JbIPS** [comment]
Alright, this looks good! Should I add a link to Docler website or maybe to another one?

And also, I noticed you called this issue 'hexMachina' but your title is 'exMachina'. Can you confim the missing 'h'? Thanks

**Comment by FrancisBourre** [comment]
Sorry for the typo, I fixed it. Docler website is Ok for me. Thanks for all.

**Comment by JbIPS** [comment]
Website updated. Closing

**Comment by ibilon** [comment]
Hey @FrancisBourre, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/1qR0zvW5Rv_g3CK3itDiDQim6Ui9PMQcRy4oExqcvmBo/edit#slide=id.g112d046e3c_0_341) on the wwx website?
