### ISSUE TITLE
request for WWX - radio clip microphones

### ISSUE THREAD

**Issue by lewislepton** [silexlabs/wwx2016#16]
this is for everyone that would be talking. but i think a rethink of microphones is in order. the ones used last year didnt sound great. plus there were tons of audio problems.

so what i would suggest is a simple radio clip mic. have 1 for everyone to use, have another as a backup which is always charged/charging. then swap after every 2 hours or so after a talk. this way it can be easy to setup.
why it would be better is because how people approached the mics in 2015, it sounded really clippy, as if the gain was way high on the mixing desk. then people were too close sounding loud which wasnt lowered, or were too far.

at least with a radio clip mic, it can stay on the person at a set length, and be handled a lot better. plus will not have troubles of feedback or anything, because of the size. so better in general.

also on a major plus side, speakers would not have to stand in one place the entire time. the speakers have to feel they can move around rather than stand like they are addressing the school with a project ;)

but this is just something to look at if you want to have better audio. either that or replace the ones on the stand ;)

**Comment by lexoyo** [comment]
:+1: 
Do you have recommendations on the model of mic please?

**Comment by lewislepton** [comment]
i will make a small list. depending for price etc ;)
just give me a few hours to collect what i have... plus dinner ;)

**Comment by ibilon** [comment]
I agree, quality is irrelevant when you're too far from the microphone ;)

**Comment by lewislepton** [comment]
well as im guessing it will be a whole system. then thats what ive looked for. and also before you think 'its how much?' this can be used for as long as possible. plus the first thing is that i do also look for price as well as build and features etc. i dont think its worth spending too much money. but some is needed ;)

now what i have looked for is battery life, range, microphone spec [whether they cut out background noise as much as possible] etc.

now. these prices on these sheets are not final. im more than sure that with a bit more of searching, you can find them cheaper etc. but this is a guide line, plus they have the spec sheets on

• $179 - Samson concert 88 presentation - looks like a really nice entry level transmitter and receiver. my only personal gripe is the microphone since its omni, rather than just cardioid. which will mean it will pick up sounds 'around' rather than just in front of it. though for the price. looks nice. 8 hour battery life on 2xAA. also has the most channel selection upto 16. good frequency response
http://www.sweetwater.com/store/detail/SWC88BLM5C

• $299 - Shure BLX14/CVL Lavalier Wireless System - this, being shure, has many good things with it. firstly, the microphone is cardioid. so will pick up more the voice than anything else. 14 hours on 2xAA. also a little lighter than the samson. 12 channels. good frequency response
http://www.sweetwater.com/store/detail/BLX14CVL-J10

• $340 - Audio-Technica System 10 Digital Wireless - slightly more than the previous. has less channels than the shure at 8 total. omni microphone. 7 hours battery life on 2xAA. good frequency response.
http://www.sweetwater.com/store/detail/ATW1101L

there is a much cheaper, but i feel too cheap make. called 'azden'. the system is about $130. but the sound is for shit, plainly. but you get what you pay for.

but its up to yourselves really. just some to have a look at. but again, there are many out and about. and even with just one transmitter, it should be fine, just some spare AA batteries would be good to hand ;)
