### ISSUE TITLE
FlashDevelop talk

### ISSUE THREAD

**Issue by Neverbirth** [silexlabs/wwx2016#17]
I'm highly considering giving a talk regarding upcoming FlashDevelop features. There are several things coming that will be of interest to many Haxe developers of every sector.

I don't know if it would be a small or big talk... there is enough stuff for more than a lightning talk, but 45 minutes may be more than needed.

What do you think? Would it be of interest?

**Comment by FrancisBourre** [comment]
I encourage this talk, knowing hector, it will be an interesting one.

**Comment by clemos** [comment]
It would be great :)
Are you in contact with @elsassph or the Flash Develop dev team ?
Maybe they already have plans regarding Flash Develop / Haxe Develop at WWX.

**Comment by elsassph** [comment]
Yes, Hector is one of the most active contributors lately! I suggested him to do a talk.

**Comment by clemos** [comment]
Sorry for not knowing hector.
To my defense, I'm not a Windows user so.... ;) :p

**Comment by elsassph** [comment]
No problem, Hector may not be very active outside of our Slack.

**Comment by JbIPS** [comment]
@Neverbirth could you give us more information on the features you want to talk about? Maybe in private if you want to keep it secret

**Comment by Neverbirth** [comment]
Sure, we can talk in private. How to reach you? Or you can write to me @ gmail.

**Comment by JbIPS** [comment]
Hello @Neverbirth, sorry for the delay I totally forget to validate your speech!

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks!

---

**Job title / occupation**

**Biography**

**Talk’s title**

**Talk’s focus & description**

**Links relevant about you and your talk**

**Comment by Neverbirth** [comment]
Sorry for not replying earlier, a lot of work and a crazy weekend. I don't like this kind of stuff heh, maybe it's good enough with this

**Job title / occupation**
Currently a Senior software developer in Docler Holding.

**Biography**
Héctor is a passionate software developer, always trying to learn and do new things and improve his skills along the way. He likes working on libraries and tools, and so he came to become one of the HaxeDevelop contributors.

**Talk’s title**
Let HaxeDevelop do more for you (not my most favourite title but I don't care much heh)

**Talk’s focus & description**
During the talk I'll show some of the most exciting stuff coming into HaxeDevelop, filling some important gaps for everyone's needs, and bringing more value for HaxeDevelop into the big enterprise world.

**Links relevant about you and your talk**
http://www.haxedevelop.org/
http://www.flashdevelop.org
http://www.flashdevelop.org/community/viewtopic.php?f=9&t=12472

**Comment by ibilon** [comment]
Thanks, could you also send us a picture of you?

**Comment by aliokan** [comment]
https://goo.gl/photos/xZEG28RmjFkkCL5FA

**Comment by JbIPS** [comment]
Little bump here, could we have your picture to announce you on the website and could you send me the timeslots where we could rehearse? Thank you

**Comment by JbIPS** [comment]
Bump again @Neverbirth :smiley:

**Comment by ibilon** [comment]
re-re-bump @Neverbirth we need it to add you and your talk to the website.

**Comment by Neverbirth** [comment]
I'm out of the country, but I talked with Jean-Baptiste by mail already last week. If you don't mind you can use the picture that aliokan posted.

**Comment by ibilon** [comment]
Oh ok, thanks, I'll add you to the website right now.

**Comment by sebpatu** [comment]
Hi, why entitle the wwx talk flashdvelop, when HF tries to promote the revamp version haxedevelop?

**Comment by ibilon** [comment]
@sebpatu the schedule had the temporary talk name, the real one is "Let HaxeDevelop do more for you" (changed on the website)

**Comment by sebpatu** [comment]
ok perfect. thanks

**Comment by ibilon** [comment]
Hey @Neverbirth, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/1Te5B-o8uiZ1TspcrWHbfzoCePSyaFsvhBYdzE5Uw7C8/edit#slide=id.p3) on the wwx website?

**Comment by Neverbirth** [comment]
Yes, sure. And I hope I'll be able to start releasing the displayed stuff soon. But anyway, anyone can contact me at my GMail account and ask for anything they want.

**Comment by ibilon** [comment]
Thanks.

**Comment by cambiata** [comment]
@Neverbirth Thank you very much for a really interesting talk, Hector! Looking forward to coming versions of Haxedevelop!
