### ISSUE TITLE
Workshop: Hacking the Haxe compiler

### ISSUE THREAD

**Issue by clemos** [silexlabs/wwx2016#18]
Pls @pleclech :p 
On our end, we can certainly invite some OCaml people to back you up ;)

**Comment by lexoyo** [comment]
:+1:

**Comment by JbIPS** [comment]
Could we hope for short lambdas? :heart_eyes:

**Comment by ibilon** [comment]
That would be nice!

**Comment by pleclech** [comment]
A big thanks for the invitation :)
Unfortunately i will not be able to attend the event :(
If i can help a little i will do, but i have not so many time on my hand.
