### ISSUE TITLE
Talk: Highway to the external world: Generate externs programmatically

### ISSUE THREAD

**Issue by andyli** [silexlabs/wwx2016#19]
Hey!
I decided to attend and speak at wwx again :)
Here is my talk proposal:

**Type**
full talk

**Title**
Highway to the external world: Generate externs programmatically

**Abstract**
Let’s face it: There are at least 100 times more libraries written in any one of the Haxe target languages than the ones written in Haxe. We don’t and shouldn’t have to reinvent the wheel all the time. And we shouldn’t spend countless hours on writing externs, which could still be incomplete and quickly become outdated.
In this talk, I will argue generating externs programmatically is the way to go. I will share my experience on generating the jQuery extern that has been merged into the Haxe standard library. I will also introduce pyextern, an extern generator for arbitrary python libraries. Possibility of generating externs for arbitrary JS/C++ libraries will be discussed.

**Comment by JbIPS** [comment]
Great proposal! I'd love to see a live example on a JS lib during the talk, is it possible?

**Comment by back2dos** [comment]
Awesome subject! Awesome speaker! :)

Is it ok with you if we announce your session?

**Comment by andyli** [comment]
@JbIPS Thanks! I will include some examples :) Not sure if I could handle an actual JS lib, but I will prepare at least some small hello-world style code to demonstrate.

@back2dos Thank you! Yes, feel free to announce it.
In case you need it, here is my profile pic: https://en.gravatar.com/userimage/4167363/9f93993fd564f3a6a494a2faf984e9f8?size=500
And my bio:

> Andy Li is a member of the Haxe Foundation, currently maintaining various aspects of the Haxe toolkit, including jQuery externs, continuous integration services, and Linux packages. He received his PhD degree in the School of Creative Media, City University of Hong Kong. He is interested in programming language theories as well as mobile user interface, interactivity, installation art and generative graphics.

**Comment by ibilon** [comment]
Now on the website.
