### ISSUE TITLE
WWX in Lanyrd

### ISSUE THREAD

**Issue by andyli** [silexlabs/wwx2016#20]
Link: http://lanyrd.com/2016/wwx2016/

I've added wwx to Lanyrd, it would be great if you can claim, or just select attend there so it looks more popular ;)

BTW, I think it would make sense to create events in other social networks. I'm not suggesting to use them as the official registration place, but just for increasing publicity. We can state clearly where should people register if they want to go in the description.

**Comment by JbIPS** [comment]
Good idea, every relay is a good thing! We'll setup events on Facebook and G+, I hope they'll be shared by the maximum of person and the Foundation.

**Comment by clemos** [comment]
Here is the FB event page, feel free to share :) 
https://www.facebook.com/events/196936004014144/

**Comment by Sayankhan** [comment]
Twit for the FB event : https://twitter.com/silexlabs/status/710091517948522496
Twit for the lanyrd event : https://twitter.com/silexlabs/status/710095485051265024
twit for the crowdfunding : https://twitter.com/silexlabs/status/707197540819714048
