### ISSUE TITLE
HF announcement

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/wwx2016#23]
Since the Foundation released a new blog last week, maybe someone could post a blog announcing the WWX?

Does someone have any contact with the blog team? @andyli @back2dos maybe?

**Comment by andyli** [comment]
Good point.
@Merelleya Would you handle that?

**Comment by Merelleya** [comment]
Heya,

Yes, I am handling the blog and already talked to Anto about a write-up. I'll get back to him and see what we can work out. Please feel free to contact me for any other communication related inquiries.

**Comment by andyli** [comment]
Thanks, @Merelleya!

While we're on it... May be we should mention wwx in the haxe.org websites. For example, a subtle "warning message" right under the navigation bar...
What do you think, @markknol?

**Comment by markknol** [comment]
```
[ BRACE YOURSELVES, THE WORLD WIDE HAXE EVENT 21016 IS COMING       (x)  ]
```

**Comment by clemos** [comment]
It would be nice to mention the crowdfunding campaign, as the priority now is for us to reach our first goal.

**Comment by kevinresol** [comment]
> 21016

:smirk:  everlasting haxe!

**Comment by ibilon** [comment]
There's now a notice for the wwx on the home page of haxe.org :)
