### ISSUE TITLE
Jive UI for mobile platforms

### ISSUE THREAD

**Issue by clemos** [silexlabs/wwx2016#25]
Hi @klmsmb

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks !

---
#### Job title

Programmer at Lanit Tercom
#### Biography

.
#### Talk’s title

Jive: UI for mobile platforms
#### Talk’s focus & description

.
#### Links

.

**Comment by klmsmb** [comment]
Job title

Developer at Lanit Tercom

Biography

I’m from Abakan, Siberia. I work in Lanit Tercom company and take a part in developments for Area 9 and The McGraw Hill Education companies. The most successful products are LearnSmart, SmartBook, SmartBuilder.
My total development experience is more than 10 years.
I started to work with Jive library about 1 year ago and like to code in it.
I'm married and have a daughter.

Talk’s title

Jive: UI for mobile platforms

Talk’s focus & description
- introduction to Jive mobile UI
- Our projects powered by Jive
- Jive roadmap

Links

https://github.com/jiveui/jive
https://twitter.com/grebenshikov_n

**Comment by ibilon** [comment]
Hey @klmsmb, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/1Xar0gWyG2DYcmYIj7iwJvJ4UG8f45Yij1IQqnhJSI9U/pub?start=true&loop=false&delayms=10000#slide=id.p6) on the wwx website?

**Comment by klmsmb** [comment]
Of course. It would be great
01 июня 2016 г. 15:17 пользователь "Valentin Lemière" <
notifications@github.com> написал:

**Comment by ibilon** [comment]
I can't seem to succeed in downloading a pdf version, could you send me one?

**Comment by klmsmb** [comment]
I'll give you access in a day. Not near my laptop. Is it OK?
01 июня 2016 г. 20:47 пользователь "Valentin Lemière" <
notifications@github.com> написал:

**Comment by ibilon** [comment]
No problem ;)
Thanks.

**Comment by klmsmb** [comment]
Do you have a google account? I want to share you original presentation.

**Comment by ibilon** [comment]
Thanks.
