### ISSUE TITLE
Highway to the external world: Generate externs programmatically

### ISSUE THREAD

**Issue by clemos** [silexlabs/wwx2016#28]
Hi @andyli 

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks !

---
#### Job title

PhD candidate in the School of Creative Media, City University of Hong Kong
#### Biography

Andy is the guy who introduced and has been maintaining CI for the Haxe Github repository for about 2 years. He is a PhD candidate in the School of Creative Media, City University of Hong Kong.
His primary research interests fall in the fields of human-computer interaction and augmented reality.
He’s the maintainer of the HaxejQuery externs and lots of other aspects of the Haxe toolkit.
#### Talk’s title

Highway to the external world: Generate externs programmatically
#### Talk’s focus & description

.
#### Links

.

**Comment by andyli** [comment]
what's "links"?

**Comment by clemos** [comment]
"Links" is for URLs to any website that may be relevant to either yourself or your talk.

**Comment by andyli** [comment]
Alright! Here is my info:

**Job title**
Developer

**Biography**
Andy Li is a member of the Haxe Foundation, currently maintaining various aspects of the Haxe toolkit, including jQuery externs, continuous integration services, and Linux packages. He received his PhD degree in the School of Creative Media, City University of Hong Kong. He is interested in programming language theories as well as mobile user interface, interactivity, installation art and generative graphics.

**Talk’s title**
Highway to the external world: Generate externs programmatically

**Talk’s focus & description**
Let’s face it: There are at least 100 times more libraries written in any one of the Haxe target languages than the ones written in Haxe. We don’t and shouldn’t have to reinvent the wheel all the time. And we shouldn’t spend countless hours on writing externs, which could still be incomplete and quickly become outdated.
In this talk, I will argue generating externs programmatically is the way to go. I will share my experience on generating the jQuery extern that has been merged into the Haxe standard library. I will also introduce pyextern, an extern generator for arbitrary python libraries. Possibility of generating externs for arbitrary JS/C++ libraries will be discussed.

**Links**
Twitter:
https://twitter.com/andy_li
Blog:
http://blog.onthewings.net/
The jQuery extern generator: https://github.com/andyli/jQueryExternForHaxe/blob/haxe3.3/js/jquery/ExternGenerator.hx
pyextern:
https://github.com/andyli/pyextern

**Comment by clemos** [comment]
Awesome !
Thanks for your responsiveness :D

**Comment by ibilon** [comment]
Hey @andyli, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/11gv3Cih2FIC5yII88Hj4x5gANjFtUbXzkw6TPYFL5WE/edit#slide=id.p) on the wwx website?

**Comment by andyli** [comment]
Sure! No problem :)

**Comment by ibilon** [comment]
Thanks.
