### ISSUE TITLE
Haxe.io Speaker Interviews

### ISSUE THREAD

**Issue by skial** [silexlabs/wwx2016#29]
Clément asked if I was interested in writing some speaker interviews, so I've written up a quick, [rough draft](https://gist.github.com/skial/f5730740edd86f788154) of some questions, initially based off the WWX2014 questions, hopefully with some improvements.

What are yours thoughts? suggestions?

**Comment by clemos** [comment]
Looks great to me :)

**Comment by skial** [comment]
Ok, I've gone over the questions again. I'm still in the process of going through each speaker and writing specific questions for each speaker. You can find the [current template](https://github.com/skial/haxe.io/blob/master/src/wwx/2016/copy_me.md) over on the haxe.io repo, ready for forking.

So if all the speakers, _who are willing_, would provide answers to the questions via a pull request, a gist, or an email, that would be awesome.
- If you don't want to answer any of the questions, no problem. 
- If there are speaker specific questions I've asked someone else that you want to answer, go for it!
- If there is a _relevant_ topic you would like to talk about, but it's not listed, please do.
- If you want to include pictures, screenshots, videos etc, add away.

/cc @jdonaldson, @dpeek, @ianharrigan, @RobDangerous, @FrancisBourre, @andyli, @nadako, @soywiz, @klmsmb, @hughsando, @waneck, @mebyz 

Did I miss anything:question:

**Comment by klmsmb** [comment]
Hi, I definitely answer those question on Monday (tomorrow).

Regards,
Max

2016-04-09 22:56 GMT+07:00 Skial Bainn notifications@github.com:

**Comment by skial** [comment]
Thats great @klmsmb :+1:

**Comment by ianharrigan** [comment]
https://github.com/ianharrigan/haxe.io/blob/master/src/wwx/2016/copy_me.md

**Comment by skial** [comment]
Write as much as you like @ianharrigan, I'll have a read a bit later today,
thanks again for taking the time to write up your answers!

**Comment by ibilon** [comment]
Hey @skial thanks for your work,

What are your plans for publishing the answers you got, before (so in the next days), during or after the conference?

Do you need help?

**Comment by skial** [comment]
@ibilon The first will be released today!

My weekend got screwed up, which I was going to use to get everything finalized and ready for release due to Monday and Tuesday be busy.

> during or after the conference?

During _could_ work, but I don't think after would be a good idea? I'm aiming to have them all out by Friday.

**Comment by ibilon** [comment]
@skial great!

Yeah before is definitely the best,
didn't want to sound "bossy" since before is only a couple of days left ;)

**Comment by skial** [comment]
> didn't want to sound "bossy" since before is only a couple of days left ;)

I didn't read it as you being bossy, so np :smile:

**Comment by skial** [comment]
I've just released @jdonaldson's [interview](https://haxe.io/wwx/2016/Justin-Donaldson/).

**Comment by skial** [comment]
Two more interviews have been released this morning, @klmsmb [interview](https://haxe.io/wwx/2016/Maxim-Bekhterev/) and @hughsando [interview](https://haxe.io/wwx/2016/Hugh-Sanderson/).

**Comment by skial** [comment]
I've just released @nadako [interview](https://haxe.io/wwx/2016/Dan-Korostelev/).

One left to release.

**Comment by ibilon** [comment]
Cool, thanks.

**Comment by ibilon** [comment]
@skial Looks like you published all of them? (thanks again)

**Comment by skial** [comment]
Yep, all done.

**Comment by soywiz** [comment]
I totally forgot about this. Cleaning up tons of emails I remembered that I was referenced here. Could/Should I still send it? Or it is finished already?

**Comment by skial** [comment]
Ooh yeah, if you wouldn't mind, it could be the first non wwx interview,
something that's come up multiple times in the past.

**Comment by jdonaldson** [comment]
Yeah it would be nice to keep these going in some way, especially for the
folks that are new and contributing.
