### ISSUE TITLE
Grand opening

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/wwx2016#3]
We're almost ready to announce the WWX date and place, so what are we waiting for? I think it would be good to send the announcing tweet around 3pm, french time, today, so it will be morning in the USA and everyone is checking his tweet feed on waking up, right?

So, if no one has objections:
- [x] Tweet - 27/01 3:00 PM (I'll write one with Silex Labs account)
- [x] Blog post - tomorrow morning for the french follower. @ibilon will you be ready?
- [x] Website - end of the week. @back2dos ok for you?

Be ready, WWX2016 is coming!

**Comment by ibilon** [comment]
Ok for me,
I'll post the article here by the end of the afternoon.

**Comment by JbIPS** [comment]
:+1:

**Comment by JbIPS** [comment]
Here's the tweet I'll post in merely an hour:

> Hello world! Come join us for the #WWX16 #haxe conf, from 05/29 til 05/29 at @MozillaParis! A lot of cool stuff coming soon, don't miss them

What do you think?

**Comment by ibilon** [comment]
let's make it more than one day ;)

**Comment by JbIPS** [comment]
Ok, but just because you asked nicely :laughing: 

> Hello world! Save the date for the #WWX16 #haxe conf, from 05/27 til 05/30 at @MozillaParis! Lots of cool stuff coming soon, don't miss them

**Comment by JbIPS** [comment]
All done! Closing
