### ISSUE TITLE
Using Haxe with Unity3D and node.js - Infos

### ISSUE THREAD

**Issue by ibilon** [silexlabs/wwx2016#30]
Hi @nadako,

Could you please fill and / or correct the following infos?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks!

---

**Job title / occupation**

**Biography**

Dan has been having fun with programming since he was seven, and is still enjoying it. He’s gone from web development in Python, through Flash/AS3 to game development using C# and Haxe. He seriously fell in love with Haxe and uses it to the max for his everyday work. He actively contributes to open-source tools he’s using, so Haxe became the main target of his open-source work.

**Talk’s title**

Using Haxe with Unity3D and node.js

**Talk’s focus & description**

**Links relevant about you and your talk**

**Comment by nadako** [comment]
### Talk description

This is a talk about one of many Haxe use cases: a language for game logic shared between client and server, both of which are programmed in different languages and environments (Unity/C# and Node.JS). We'll cover how we ended up with Haxe, how it worked out, what issues did we have and how we dealt (or not) with them.

### Relevant links

related to me: http://github.com/nadako
related to the talk: http://nadako.tumblr.com/post/113390739725/a-success-story-for-haxe

---

Is that enough?
Bio sounds fine.

**Comment by ibilon** [comment]
Yes, thanks!

**Comment by ibilon** [comment]
Hey @nadako, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/1VhrANgtfdEGQew4CRDeEESkA2eGFgGf1EnQCHIS1kUc/edit#slide=id.p) on the wwx website?

**Comment by nadako** [comment]
Sure!

**Comment by ibilon** [comment]
Thanks.
