### ISSUE TITLE
Haxe React Magic - Infos

### ISSUE THREAD

**Issue by ibilon** [silexlabs/wwx2016#31]
Hi @dpeek,

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks!

---

**Job title / occupation**

**Biography**

David is a Flash Platform refugee that escaped the persecution of Adobe by crossing the border into the Haxe promised land. His only regret is the years of lost productivity waiting for MXMLC to finish compiling. He now focuses on bringing stability and quality to the Haxe development process at Massive through tools, libraries and processes. He has a  fetish for porting libraries to Haxe (semver, mmvc, minject, markdown), fought long and hard to get Haxe and Neko into homebrew, wrote the dox documentation generator with Simn, and broke all sorts of bash conventions in hvm. He'll almost certainly be the tallest person at WWX.

**Talk’s title**

Haxe React Magic

**Talk’s focus & description**

**Links relevant about you and your talk**

**Comment by ibilon** [comment]
Hey @dpeek, (maybe @elsassph #11?)
Can you please give us these infos so we can announce your talk ?
Thanks in advance

**Comment by dpeek** [comment]
_Job Title_
Solutions Architect

_Biography_
That's fine.

_Talks Title_
Either the current one maybe this one is cute:
typedef React = State -> View;

_Talk's Focus_
Whether or not you've jumped on the React bandwagon, it has introduced (or at least popularised) some powerful new approaches to building and thinking about user interfaces. In this talk I'll show you how a sprinkling of Haxe can make things even better. Come on, all the cool kids are doing it.

_Links_
https://facebook.github.io/react
https://github.com/massiveinteractive/haxe-react

**Comment by ibilon** [comment]
Thanks

**Comment by ibilon** [comment]
Hey @dpeek, are you getting my emails? I hope I didn't use the wrong address,
contact me ASAP, my email is in my profile.

**Comment by elsassph** [comment]
Hey it turns out that I'll have to impersonate David again this year, please contact me.

**Comment by ibilon** [comment]
Alright, shouldn't be an issue, I'll just replace David with you on the website.
Should we reuse the bio/picture from last year?
Also I can't seem to find your email address, just send me an empty email and I'll reply ;)

**Comment by elsassph** [comment]
Mmmh try my name at Gmail. Can't find your email either.
Previous photo and bio is probably ok.

**Comment by ibilon** [comment]
Hey @dpeek @elsassph, would it be ok for us to upload your presentation (https://onedrive.live.com/view.aspx?resid=4612536FAA245E80!10817&app=PowerPoint&authkey=!ALB82j-WAYN4Z-o) on the wwx website?

**Comment by elsassph** [comment]
Yes sure.

**Comment by ibilon** [comment]
Thanks.
