### ISSUE TITLE
hxcpp roundup talk

### ISSUE THREAD

**Issue by hughsando** [silexlabs/wwx2016#33]
Are there any normal talk spots left?  I think I can git a hxcpp roundup talk.

**Comment by back2dos** [comment]
Oh, yes please! :)

**Comment by clemos** [comment]
Yes, there is always room for hxcpp, we would be very happy to welcome your talk :)
Please confirm, and send us a photo, speech title and job title so we can announce it on the website.

**Comment by hughsando** [comment]
Ok, I have booked my flights!
Talk:  Hxcpp - what's new()
Job:Lead Software Engineer at Dynamic Digital Depth
Photo: It is pretty tricky to get a good photo of me.  Last year there was a professional photographer there - but I did not see the results.  Maybe there is something there.  Otherwise I can dig something up.

**Comment by clemos** [comment]
Thanks a lot :)
You can find links to last year's Flickr photo albums here : https://www.silexlabs.org/wrapping-up-wwx2015/

**Comment by hughsando** [comment]
The photographer actually took me aside for some head-shots for the haxe website or something, and these are not in the general album.  Maybe his camera rejected me.

**Comment by clemos** [comment]
The camera seemed ok with your face :) do you mean these : 
https://www.flickr.com/photos/120854033@N02/19280989250/in/album-72157655029592122/
https://www.flickr.com/photos/120854033@N02/18846029324/in/album-72157655029592122/

**Comment by hughsando** [comment]
No - we went into the lobby and took some with just me to get a clear
background.

**Comment by andyli** [comment]
Indeed I also took such head-shots but have never seen the pics... Maybe @ncannasse knows where the pics went?

**Comment by ncannasse** [comment]
Requested them several times to SilexLabs, never got a reply :'( I think I only got yours, Andy :)

**Comment by clemos** [comment]
I'm sorry, I don't know what you're talking about...
Meanwhile, you may want to choose a pic among those we published ;)

**Comment by hughsando** [comment]
Yes, thought I may have broken the camera.
Lets go with this one:

https://www.flickr.com/photos/120854033@N02/18959148409/in/album-72157654643151058/

Thanks for organizing stuff.

Hugh

**Comment by clemos** [comment]
Thanks :)
I checked it with the team, and it turns out your face indeed broke the camera. 
Sorry about that.

**Comment by ncannasse** [comment]
@clemos we kindly asked the photographer at WWX 2015 to take shots of team members for the website, which he agreed (I asked through chloe), but we didn't get the pictures

**Comment by ibilon** [comment]
Added you to the website.

Next step is a biography (if you want to change from the one used last year),
the talk’s focus & description,
and links relevant about you and your talk.

**Comment by hughsando** [comment]
Hey,
Sorry have not got onto this - had a bit extra to do getting hxcpp to work for the current release.
As far as Bio goes, it is going to be easiest to reuse last years, although you can chalk up an extra year on my haxe dev clock.
Talk:
Quite a bit has gone on under the hood of the hxcpp backend this year.  Find out what  a low-level rewrite of the garbage collector, a refactor of the ocaml code and improved representations of objects, enum and interfaces means to you.   With lots of community support this year,  the native integration has been driven forward, and this talk may help you find easy ways to integrate hxcpp into your projects.

**Comment by ibilon** [comment]
Hey @hughsando, couldn't find your presentation online, could you upload it? (or send us a link if I just missed it)
Also would it be ok for us to upload it on the wwx website?

**Comment by hughsando** [comment]
I have published them on http://gamehaxe.com/2016/06/01/wwx2016/

Feel free to re-host the swf if you like.

**Comment by ibilon** [comment]
Thanks.
