### ISSUE TITLE
The Haxe Lua target - Infos

### ISSUE THREAD

**Issue by ibilon** [silexlabs/wwx2016#35]
Hi @jdonaldson,

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks!

---

**Job title / occupation**

**Biography**

**Talk’s title**

The Haxe Lua target

**Talk’s focus & description**

**Links relevant about you and your talk**

**Comment by jdonaldson** [comment]
# Job title / occupation

Lead Data Scientist -  Salesforce.com, Inc.

# Biography

Justin Donaldson is currently a Lead Data Scientist at Salesforce.com, where he uses machine learning to tackle a variety of difficult natural language problems.  He also has worked as a search relevance engineer, and a front end developer on a wide range of projects.  In the recent past, he cofounded BigML, and developed the information visualizations that are used there to represent decision trees and support exploratory analysis of data.  Prior to that, he worked on recommender systems in both an academic setting (for a PhD), and in an industry setting. He's also the proud father of a new 1 1/2 year old, and he lives in Seattle, Wa.

# Talk’s title

Shooting for the Moon : Haxe Lands on Lua

# Talk’s focus & description

Lua is a language that can play many roles: A light-weight memory-safe scripting environment suitable for embedded devices, a speedy jit with a flexible C FFI for high performance web development,  or even the language for a state of the art machine learning framework.  However, as a scripting language Lua suffers from the same scalability problems that plague large dynamic language codebases.  

Haxe's ability to effectively organize and compose projects makes Haxe/Lua projects an ideal approach for developing complex Lua applications.  This talk will cover the basics of how the Haxe language maps to Lua internals, and cover some useful topics such as avoiding pitfalls, using helpful workarounds, and getting the most out of your next Haxe/Lua project.

# Links relevant about you and your talk

None yet, although a blog post is pending.

**Comment by ibilon** [comment]
Hey @jdonaldson, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/1evvd_v5G3d9jE-VPCjeCi85l4FW6EjmSEF77Qmq-t1M/edit#slide=id.p) on the wwx website?

**Comment by jdonaldson** [comment]
Sure thing!  Have at it.

**Comment by ibilon** [comment]
Thanks.
