### ISSUE TITLE
Jive workshop !

### ISSUE THREAD

**Issue by clemos** [silexlabs/wwx2016#40]
I've just been attending @klmsmb's rehearsal about Jive for mobile.
The presentation is great, and he told me he was interested in giving a workshop about Jive on monday, together with @ngrebenshikov :D 
We are in the process of setting it up (schedule, ...), but meanwhile, people interested in participating are welcome to register here.

**Comment by clemos** [comment]
Hey @klmsmb and @ngrebenshikov,
We're planning to do your workshop on monday, from 10am to 11:30am.
Is it ok for you ?
Can you tell us in a few words what you plan to do for this workshop ?
For now I've put:

> In this workshop, we will help you get started with Jive UI, the cross-platform UI framework for Haxe.

**Comment by klmsmb** [comment]
Hi, @clemos 
Yes, time is fine.
Our idea about workshop is to create some form with few elements and layout it. So you was 100% right about our plan and can leave it in your variant.
