### ISSUE TITLE
Kha workshop !

### ISSUE THREAD

**Issue by clemos** [silexlabs/wwx2016#41]
I just saw @robdangerous' rehearsal talk via Skype, 
and it was awesome and mind-blowing as always :)
He agreed to give a workshop on Kha / Kode on monday, preferably morning.
So this thread is to set it up, and potentially for people to let us know if they're interested to attend :)
Looking forward to it.

**Comment by ibilon** [comment]
Nice! Always wanted to try kha but never found the time, perfect occasion.

**Comment by clemos** [comment]
Hey @robdangerous,
We're planning to do your workshop on monday, from 1:30pm to 3pm.
Is it ok for you ?
Can you tell us in a few words what you plan to do for this workshop ?
For now I've put:

> In this workshop, we will help you get started with Kha, the super portable software dev kit.

**Comment by RobDangerous** [comment]
Yes, timing is ok.
"In this workshop we will help you to get started with Kha, the super portable software dev kit and its accompanying IDE Kode Studio. Kha's programming workflow and its capabilities for 2D and 3D graphics are introduced, including some shader and SIMD programming."
