### ISSUE TITLE
Presentation Template / Haxe Logos

### ISSUE THREAD

**Issue by markknol** [silexlabs/wwx2016#44]
I want to let know to the speakers that there is a standard template for presentations, in case anyone needs one.

https://docs.google.com/presentation/d/1Ax9mZm0-H3rvQ4gRXbtIsh7BNW7NyYVg4y-AK9HJcEk/edit?usp=sharing

Also you can pick different versions of the logo on the Haxe branding page  http://haxe.org/foundation/branding.html

**Comment by clemos** [comment]
Oh this is nice, thanks :)
