### ISSUE TITLE
Secret Stack - Infos

### ISSUE THREAD

**Issue by ibilon** [silexlabs/wwx2016#45]
Hi @lexoyo,

Could you please fill and / or correct the following infos ?
The "Bio" and "Talk's focus and description" fields will be used in the full schedule, and other communication material.
Let me know if you need any more infos.
Thanks!

---

**Job title / occupation**

**Biography**

**Talk’s title**

Secret Stack

**Talk’s focus & description**

**Links relevant about you and your talk**

**Comment by lexoyo** [comment]
Sorry about the delay
I already made corrections to the wwx website
Tell me if I should add this somewhere
Thx

**Job title / occupation**

President @ SIlex Labs. Partner @ Secret Media.

**Biography**

Alex Hoyau is a senior front end developer, architect and team leader in the development of web applications. 

**Talk’s title**

The Secret Stack.

**Talk’s focus & description**

At Secret Media we tackle the hotest issue of today's web: the unacceptable practices of advertisers. Secret Media has taken a very complex challenge: to fix it with only tech, and without anyone noticing it. The technical solution is made of Haxe and sweat, that's the secret stack.

**Links relevant about you and your talk**

-no link, this is secret-

**Comment by ibilon** [comment]
Hey @lexoyo, would it be ok for us to upload your presentation (http://secretmedia.github.io/WWX2016-secret-talk/) on the wwx website?

**Comment by lexoyo** [comment]
yes of course!!

**Comment by ibilon** [comment]
Thanks.
