### ISSUE TITLE
stream url?

### ISSUE THREAD

**Issue by andyli** [silexlabs/wwx2016#46]
Has the live stream url been decided yet?
I think it would be good to update haxe.org's banner with it. :)

**Comment by skial** [comment]
I'll attempt to do the same on haxe.io

**Comment by Sayankhan** [comment]
Stay tuned we will communicate it ASAP but it will be probably on http://wwx.silexlabs.org/2016/

**Comment by markknol** [comment]
@andyli Do you have time to update this, otherwise I can help.

Maybe we can do something like this: 

> Follow the world wide Haxe event livestream this weekend (may 27-30) on http://wwx.silexlabs.org/2016/

**Comment by andyli** [comment]
Yes, it would be great if you can help since my macbook is out of order
right now..

**Comment by markknol** [comment]
Ok ill do it tonight.

**Comment by markknol** [comment]
Done. It's on the internet : http://haxe.org/

**Comment by andyli** [comment]
That was fast! Thanks a lot! :)
