### ISSUE TITLE
The Haxe Lua Target 

### ISSUE THREAD

**Issue by jdonaldson** [silexlabs/wwx2016#5]
I'd like to talk about the [Lua target](https://github.com/jdonaldson/haxe/commits/haxe_lua_rb3.2) I've been working on.  It's in pretty good shape, passing all but a few tricky Issue<#>.hx tests.  I'm working with Simon to iron out any remaining kinks.

**Comment by nadako** [comment]
This is awesome! Looking forward for that talk and lua target to become a part of official Haxe!

**Comment by back2dos** [comment]
Yes please!

**Comment by jdonaldson** [comment]
Kudos to @Simn and @PeyTy for sorting out the remainder of the failing tests!  Now we're going to give it some more love.

**Comment by PeyTy** [comment]
@jdonaldson You can now make this, like @hughsando did in http://gamehaxe.com/wwx/wwx2015.swf for CPPIA target :yum: 

![image](https://cloud.githubusercontent.com/assets/3642643/12757831/b8c04c80-c9ea-11e5-94d8-4a53e9cf355d.png)

**Comment by jdonaldson** [comment]
Pure joy!

``` bash
16:53 $ ../../haxe compile-lua.hxml  
Test.hx:294: Generated at: 2016-02-02 16:53:36
Test.hx:296: START
Test.hx:221: DONE [6293 tests]
Test.hx:222: SUCCESS: true
```

**Comment by nadako** [comment]
That is awesome!!!

BTW there are some issues with Lua 5.3 new integers, see my e-mail. Also @Simn check that email too, I finally compiled all required libs on Windows :)

**Comment by clemos** [comment]
We're about to finish the website.
Do you mind if we announce your talk on the website ?
Can you send us a bio and picture, as well as a title for the talk ?

**Comment by jdonaldson** [comment]
Hey sure, that's awesome!

Here's a pic:
![12522977_10208737211172487_4660778519258467509_n](https://cloud.githubusercontent.com/assets/41479/13129337/362b88d6-d591-11e5-9c8c-29420a1a8e36.jpg)

bio:

Justin has been a Haxe fan since early 2006.  He's a Ph.D. and veteran startup cofounder, Data Scientist, and (recently) new father. However, he still finds time to work on his favorite Haxe related projects.  He wishes more Haxe folks were in the Pacific Northwest.

title:

Shooting for the Moon : Haxe lands on Lua.

**Comment by back2dos** [comment]
Awesome pic! Do you mind if we edit out the dude with the silly sunglasses? :D

**Comment by jdonaldson** [comment]
Hey now, I resemble that remark!

**Comment by JbIPS** [comment]
Talk's on the website, closing.

**Comment by back2dos** [comment]
@JbIPS If we're doing rehearsals this year, then maybe these issues should be relabeled instead of closed.

**Comment by JbIPS** [comment]
We'll do rehearsals for sure, but we thought planning it only concerned the speaker and didn't need to stay here.

But maybe you still have some use in mind for these issues?

**Comment by back2dos** [comment]
Nope just that. You're right, it would probably generate too much noise here.
