### ISSUE TITLE
Jive UI for mobile platforms (lightning speech)

### ISSUE THREAD

**Issue by ngrebenshikov** [silexlabs/wwx2016#6]
I'd like to share with the community how we developed the first mobile application (iOS, Android) using Jive.
Main points:
1) mobile UI components in Jive;
2) native text inputs and other OpenFL extensions;
3) one UI layout for many screen resolutions.

**Comment by ibilon** [comment]
Would you want to do a full talk (~40min) or a lightning talk (~15min) about that?

**Comment by ngrebenshikov** [comment]
I'd like to have a lightning talk (~15min).

**Comment by ngrebenshikov** [comment]
Hi, @ibilon. We'd like to change a speaker to Maxim Bekhterev. We'll prepare the speech together and will attend the WWX together as well. 8)

**Comment by JbIPS** [comment]
Hi, @ngrebenshikov ! Could you give us some info on the new speaker so we can announce this lightning talk?

**Comment by klmsmb** [comment]
Hi, my name is Maxim, and I am from Abakan, Russia. I work as a programmer at the Lanit Tercom company. I began to work with Jive about a half year ago and was impressed at how easily it was to create mobile applications there. So I joined to Nickolay Grebenshikov and together we are working to improve Jive.

**Comment by JbIPS** [comment]
Great! Could you link us to a picture too?

**Comment by klmsmb** [comment]
https://drive.google.com/file/d/0B6G3SYwURwFGQ19lYU1GdkkzN0E/view?usp=sharing
could you try this one?

**Comment by JbIPS** [comment]
Perfect, I'll set this up quickly!

**Comment by ngrebenshikov** [comment]
@ibilon, could we have any invitation letter from SilexLabs? It'll make the process of getting a french visa much simpler.

**Comment by clemos** [comment]
@ngrebenshikov Sure, we'll prepare an invitation letter tomorrow. For both Maxim Bekhterev and you ?

**Comment by ngrebenshikov** [comment]
Yes, for both.

**Comment by ibilon** [comment]
Added to the website, sorry for the delay!
