### ISSUE TITLE
pistahx : Type-safe, design-first haxe web api

### ISSUE THREAD

**Issue by mebyz** [silexlabs/wwx2016#7]
I'm actively working on the development of pistahx, (formerly named orms)  : a Design-First Haxe Web API Framework :

http://www.pistahx.io

https://github.com/mebyz/pistahx (haxe core)
https://github.com/mebyz/pistahx-spec (yaml > haxe type typedefs)
https://github.com/mebyz/pistahx-db (db > haxe typedefs)
- https://github.com/mebyz/pistahx-app (sample api using pistahx, useable to bootstrap your app)

I would like to propose a presentation about it during wwx2016 :  

If you plan to develop a Web API using the Haxe Language, pistahx will give you both a modern and strong technical toolset and a fast and simple developpement workflow.

here are pistahx key concepts :
- PERFORMANCE : pistahx heavily relies on it's multiple cache layers
  Custom output cache for each route based on your api specs
  Secure Cookie based Session / Auth token Redis store
  Pro-active cascading cache invalidation strategies
  Db caching (via Sequelize) : use cache to store entities and queries
  Define your own caching strategies for fine tuning
- SECURITY : pistahx offers you multiple authentication strategies, which you can easily activate from your configuration file ( ./your_pistahx_app/conf/[env].yaml ) :
  JSON Web Tokens (JWT) : if you want to build RestFULL APIs or if you have to deal with cookie-less clients
  Standard but fast and secure sessions strategy if you're setting up a service targeting Web browsers supporting cookies
  pistahx also implements Passport.js (which includes 300+ more auth strategies) !
  MONITORING: pistahx offers you instantaneaous monitoring with the support of the gorgious ELK stack and Appmetrics library. Simply fill ELK_SERVER parameter in conf file and you're good to go !
- DESIGN FIRST : with pistahx, your API description/spec can be easily changed using a simple language paradigm (yaml)
- MOCK YOUR TESTS IN THE SPEC DESCRIPTION : simply mock some test cases (a request and its response) in the YAML spec and let mocha (via swagger-test) do the magic !
- AUTOMATIC DOCGEN : an interactive documentation is automatically generated from the spec
- AUTOMATIC CODEGEN : API server code (routing, server core...) is automatically generated from the spec
- CODE LOGIC SEPARATION : Business logic is separated from the server core code
- STRONGLY TYPED CODE : The business logic is written in Haxe (type checking helps the code to stay clean and secure), before being transpiled to nodejs code
- OPEN SOURCE, MULTIOS, FAST BOOTSTRAPPING STACK: pistahx can be set up, modified and deployed everywhere nodejs code can run. Unix/Linux, Windows, OSx, ...
- MULTIDB: pistahx uses Sequlize, which alllows you to connect to mssql, mysql, pgsql, sqlite,... databases
- PROMISES-FULL : Use the mighty power of Promises using a simple Haxe (Promhx) workflow :
- DB PROMISES: SEQUELIZE too handles parallel db querying strategies :
- CONTAINER READY: pistahx gives you a native docker container environment for your app. You're finally able deploy everywhere

**Comment by ibilon** [comment]
Would you want to do a full talk (~40min) or a lightning talk (~15min) about that?

**Comment by mebyz** [comment]
I'll try to prepare a lightning talk for this first presentation of pistahx 
- small context and goals presentation
- pistahx technical presentation
- sample workflow / live demo

That being said, I could also arrange a full talk, with more insights and workflow examples, if the community wants to dig more in the subject :
- bootstrap your own api with pistahx
- testing, continuous integration, industrialisation of pistahx
- cloud deployment of pistahx-based apis
- full live demo from 0 to functional rest api

**Comment by back2dos** [comment]
Personally I think the last point "full live demo from 0 to functional rest api" is _very_ interesting. I think this can be really hard (finding a problem with just the right complexity), but if you feel up to it, then I think it should be the centerpiece of the talk. There are many grand ideas but seeing the implementation at work tends to be quite eye-opening.

**Comment by mebyz** [comment]
Thanks for your message @back2dos.

Alright then, let's go for a long talk.
I'll try focus as much as possible on the  "0 to functional rest api" journey using pistahx, within a (fictive)real-case production workflow scenario.

I'll try to post a clean summary here, so everyone can review it before D-day

**Comment by JJayet** [comment]
+1 would love to have a presentation of ORMS

**Comment by mebyz** [comment]
thanks for your support !

**Comment by mebyz** [comment]
I'm starting organizing things for pistahx (formerly "orms") talk, and I wondered :

Is that ok for you guys if my demo relies on an cloud-based aws architecture ? The stack would include postgresql server, redis server, and linux instances, all deployed in aws cloud and ruled by aws elastic beanstalk.

While orms could be deployed on any stack even locally, I think there will be more interest if i show something that is more than just a local api getting it's data from a simple local sqlite db ;)

what do you think ?  are cloud deployment-problematics one of your concerns ? 

Also, if you guys want me to talk about some specific api-related problems you may have had, maybe I can try to think of it and prepare something during the talk by integrating theses cases 

Feel free to tell me. Thanks in advance !

**Comment by JbIPS** [comment]
I don't mind a cloud-based architecture if you skip the AWS setup phase because it takes ages :smile:

**Comment by mebyz** [comment]
@JbIPS I will of course avoid the aws setup phase while presenting the demo. Everything will be ready, so we can focus on the real work using pistahx (formerly "orms") itself.

I just chose to use an aws stack for the demo to show you "a cloud-based implementation" of pistahx (formerly "orms"), but we won't loose much time there, got it.

**Comment by back2dos** [comment]
My advice is not to worry too much about specific details but try to get a good flow that strings together all the strong points of your solution. You have to inspire the will in people to deal with the details themselves, because that's what it means to pick up a 3rd party tool. Still, there's also time allotted for questions. So for example if someone asks "can I host it on my own server" you say "yes, of course" and that's that ;)

**Comment by mebyz** [comment]
Thanks a lot for your advices ;)

**Comment by ibilon** [comment]
Sorry for the delay,
could you send us a photo and biography so we can announce your talk on the website?

**Comment by mebyz** [comment]
No worries Ibilon.

I'm working hard on this pistahx (formerly "orms") project these days, many many things are on the way so I can make a nice presentation by the end of May, and hopefully spark an interest among the Haxe community.

here is a photo of me https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/4/000/135/130/0976fed.jpg and a small bio (let me know if it fits your needs or not):

"Cultivating a true passion for coding, Emmanuel (mebyz on github) has always been thrilled to discover new technologies and programming languages. Always happy to talk about (and build) continuous integration strategies, software architecture designs, industrialisation processes, along with many other subjects (3d, functionnal programming, optimisation problematics, ..), Emmanuel also loves to dig in the human aspects of any IT projects : constant improvement by knowledge-sharing and pedagogy is one of its #1 priority. He discovered Haxe language a few months ago and has been an addict since then, using it on a daily basis for both professionnal and personnal projects."

(thanks in advance if ever there is a mistake somewhere !)
Last thing, if you need a catch sentence for pisthx (formerly "orms") project Introduction itself, feel free to ask

Thanks !

**Comment by mebyz** [comment]
## !! since then, orms has been renamed to = > pistahx

By the way, some people around me don't like the "orms" name that much (too close to "orm" : "object relational mapping" term), so I'm thinking about renaming it. the truth is orms is clearly NOT an orm and should not be considered as such.
Anyhow, here are some of my ideas for a new name (if ever you guys feel I'm wrong somewhere, feel free to tell me!) : 
- cachew.io (orms heavily relies on cache strategies, smart cache invalidation, .. also I love cashew nuts)
- swagmidable.io (orms relies on the swagger spec, but sadly swagger has been renamed to openapi now..)
- ormidabl.io (because it's fun)
- agnostack.io (I'm working on a Typescript integration branch, so orms could become "language agnostic" soon, giving the developper the opportunity to choose between haxe, ts, ...)
  -..  ?
- keep the "orms" name even if there's a risk of misleading ?

I also wonder if i should rename the project asap (as in "before D-day / wwx2016") or just after.

What do you guys think about this ?

**Comment by ibilon** [comment]
Yet again sorry for the delay, I have a lot of works these days.

Could you send us a job title or something alike the ones found here http://wwx.silexlabs.org/2016/#speakers

In my opinion I think you need a name for the day of the wwx, since people may remember it and search for it, but until then it should be ok to stay "unnamed project 1" :)

**Comment by mebyz** [comment]
Hi again, please do not worry ;)

"Back-End Engineer at LeKiosk" should do it for my job title

I'm still thinking about a name, I'll try to decide this before the end of this month ( approx one month before wwx)

sounds ok ?

**Comment by ibilon** [comment]
Sounds good, added you to the website.

**Comment by mebyz** [comment]
Thanks a lot @ibilon. 

A question from my fellow coworkers @ LeKiosk : 
"are there still some tickets/seats available for us to register before the event ?" (2 or 3 seats min, beside myself)
is there a registration form somewhere ? (did not find it, sorry)

I guess my seat is reserved, as I'm listed as a Speaker, but don't hesitate to tell me if I also need to register somewhere before wwx2016.

Beside this, I'm trying to prepare answers to the "speakers" questions list (https://github.com/silexlabs/wwx2016/issues/29)

thanks again !

**Comment by clemos** [comment]
Hey @mebyz 
Maybe LeKiosk would be interested in sponsoring the event, then ;) ? 
All sponsor packs and corresponding rewards listed on the [crowdfunding page](https://www.ulule.com/wwx2016/) can still be purchased directly with Silex Labs (contact@silexlabs.org), since the ulule campaign is over.
Also, LeKiosk being a French company (?), sponsoring the conference via Silex Labs (a French non-profit) may mean tax reduction.

As for individual tickets/seats, we're still unsure as to when and how we will make them available.

**Comment by clemos** [comment]
PS: Of course, as a speaker, your seat is reserved ;)

**Comment by mebyz** [comment]
hi @clemos, thanks for the tips and answers ;)

After a looot of thoughts, orms project has been renamed to "pistahx" !

http://www.pistahx.io/ ( Design-First Haxe based Web API Framework )

 3 repos (+1 bootstrap sample app) :
- https://github.com/mebyz/pistahx  (core of the project, haxe based)
- https://github.com/mebyz/pistahx-spec (yaml models to haxe typedefs transpiler written in haxe)
- https://github.com/mebyz/pistahx-db (database models to haxe typedefs transpiler written in haxe)
- https://github.com/mebyz/pistahx-app (sample api using pistahx, useable to bootstrap your app)

**Comment by ibilon** [comment]
Got it!

All that's missing is a description of the talk.

**Comment by mebyz** [comment]
Alright : this description should be ready in about 2/3 days max. I'll post
it right here when ready !
Le 27 avr. 2016 13:45, "Valentin Lemière" notifications@github.com a
écrit :

**Comment by mebyz** [comment]
Hi all

Some updates for Pistahx my presentation : 
1. I've been confirmed for a presentation slot on Saturday 28th around 11am !
2. here is a catch phrase for the project : "pistahx : type safe, design first, haxe web api"
   => could someone please correct wwx's website to show this project's name and catchphrase (under my picture ?) thanks a lot
3. I'm still working on the interview Q&A
4. I'm actively working on the presentation itself. should be ready around May 15

Feel free to ask me if I miss something !
http://www.pistahx.io

**Comment by ibilon** [comment]
I'll do the update today,

when you have a description please send it to us so that I can add the talk page on the website.

**Comment by ibilon** [comment]
Updated ;)

**Comment by mebyz** [comment]
Here is the description of the project ( feel free to tell me if I made any mistake ;) )

**PISTAHX : Type-safe, design-first, haxe web api**
Created for WEB API developers, **pistahx** is an effort to address some (common) problematics : Old & slow legacy code and development tools, Heavy costs due to technology stickiness (licenses, infrastructure), Inexistant API documentation  or specification, Performance issues, bad caching strategies, Scalability / deployability issues etc..

Pistahx is a performant and scalable, design-first web api framework. Based on Haxe, it helps helps coders write clean and type-safe business classes. Targetting the Nodejs ecosystem, your api can be deployed and scaled on almost any stack/cloud. We also offer a minimal dockerhub image (pistahx-docker-stack) to help you deploy your api in docker containers. Pistahx uses Redis as an ultra-fast cache store (multiple cache layers are available). Pistahx implements the OpenAPI specification (formerly known as swagger) and auto-generates your interactive documentation.You can use additional modules to generate Haxe typedefs from your API specification (pistahx-spec), and/or from your DB schema (pistahx-db, optional) among many other stuff.

Emmanuel BOTROS YOUSSEF (mebyz)
http://www.pistahx.io

Thanks !

**Comment by ibilon** [comment]
Hey @mebyz, would it be ok for us to upload your presentation (https://docs.google.com/presentation/d/1QT-05nxviXKBoOpX02-qTV5YTvSuOZkD3aKaoBJ_f0M/edit#slide=id.g11337e21a8_2_50) on the wwx website?

**Comment by mebyz** [comment]
Of course ! Thanks a lot :)
Le 1 juin 2016 10:20, "Valentin Lemière" notifications@github.com a écrit
:

**Comment by ibilon** [comment]
Thanks.
