### ISSUE TITLE
integrating haxe for shared code

### ISSUE THREAD

**Issue by nadako** [silexlabs/wwx2016#8]
I am not yet sure, but I'm thinking about giving a 15min talk about how I used haxe together with node.js and unity3d. Basically a short version of my [earlier post](http://nadako.tumblr.com/post/113390739725/a-success-story-for-haxe). Would something like this be interesting to attend to?

**Comment by nadako** [comment]
Also, before I dive into google, what's a good software to make presentations with? Something that can be written in a text editor and hosted on github easily is preferable :)

**Comment by markknol** [comment]
I created some demo slides in Google Slides to be used as template for any Haxe related presentation. It has copy/pastable slides. You can use this if you want. 
https://docs.google.com/presentation/d/1Ax9mZm0-H3rvQ4gRXbtIsh7BNW7NyYVg4y-AK9HJcEk/edit?usp=sharing

**Comment by nadako** [comment]
Thanks! That looks very cute! I guess google presentations would work too.

**Comment by ibilon** [comment]
I've seen several people use https://github.com/hakimel/reveal.js to make their presentation,
it's html and you can host it easily with revealjs as a submodule.

For the lightning talk we've seen your proposition,
we are waiting to have more submissions before making a decision,
but we think the subject would make a good talk.

**Comment by ibilon** [comment]
We're about to finish the website.
Do you mind if we announce your talk on the website?
Can you send us a bio and picture, as well as a title for the talk?

**Comment by nadako** [comment]
Can this wait a bit? I'm still not completely sure I'll be able to give that talk.

**Comment by back2dos** [comment]
Of course, that's why we're asking ;)

**Comment by nadako** [comment]
Ok, I think I'll be giving this talk after all. I'll prepare some bio and a picture later.

**Comment by back2dos** [comment]
Awesome! :)

**Comment by JbIPS** [comment]
@nadako Quick reminder for your bio and pic :wink:

**Comment by nadako** [comment]
I had some trouble finding a recent picture of me but finally here it is :)
![Dan Korostelev](http://i.imgur.com/MlvTmU9.jpg)

Bio (feel free to edit as my english is not perfect):

Dan has been having fun with programming since he was seven, and is still enjoying it. He’s gone from web development in Python, through Flash/AS3 to game development using C# and Haxe. He seriously fell in love with Haxe and uses it to the max for his everyday work. He actively contributes to open-source tools he’s using, so Haxe became the main target of his open-source work.

I haven't come up with a funny title yet tho :)

**Comment by nadako** [comment]
Oh well, let's just call it "Using Haxe with Unity3D and node.js" as I won't be able to come up with a fun title until I actually start working on the presentation :)

**Comment by ibilon** [comment]
Added to the website, sorry for the delay!

**Comment by nadako** [comment]
Nice! Now I just have to start writing that talk :)
BTW, what's with the aspect ratio of pictures on the wwx website?
